package client;

import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
        private String id;
        private String geneFileTxt;
        private String geneTxt;
        /**
     * Creates new form MainForm
     */
    
        
    public MainForm() {
        initComponents();
    }
    
    private void set_geneFileTxt(){
        // TODO add your handling code here:
        id = sequenceIdTxt.getText();
        System.out.println(id);
        this.geneFileTxt = gene(id);
        System.out.println(geneFileTxt);
    }
    private void set_geneTxt(){
        this.geneTxt = SequenceTxt.getText();
    }
    
    private void format_geneTxt(){
        set_geneTxt();
        this.geneTxt=geneTxt.replaceAll("[\\r\n\\s]","");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        GeneSequenceAnalyzerpnl = new javax.swing.JPanel();
        GeneSequenceAnalyzerlbl = new java.awt.Label();
        sequencePnl = new javax.swing.JPanel();
        java.awt.Label sequenceLbl = new java.awt.Label();
        SequenceTxt = new javax.swing.JTextField();
        loadSequenceBtn = new javax.swing.JButton();
        clearSequenceBtn = new javax.swing.JButton();
        sequenceIdTxt = new javax.swing.JTextField();
        javax.swing.JButton okBtn = new javax.swing.JButton();
        cancleBtn = new javax.swing.JButton();
        resultTxt = new javax.swing.JTextField();
        formatSequenceBtn = new javax.swing.JButton();
        computeBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        ComputeSequencePropertiesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        GeneSequenceAnalyzerlbl.setAlignment(java.awt.Label.CENTER);
        GeneSequenceAnalyzerlbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GeneSequenceAnalyzerlbl.setText("Gene Sequence Analyzer");

        sequenceLbl.setAlignment(java.awt.Label.CENTER);
        sequenceLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        sequenceLbl.setText("Sequence Id :");

        loadSequenceBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loadSequenceBtn.setText("Load sequence ");
        loadSequenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSequenceBtnActionPerformed(evt);
            }
        });

        clearSequenceBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearSequenceBtn.setText("Clear sequence");
        clearSequenceBtn.setToolTipText("");
        clearSequenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSequenceBtnActionPerformed(evt);
            }
        });

        sequenceIdTxt.setText("Sample1");
        sequenceIdTxt.setToolTipText("");
        sequenceIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequenceIdTxtActionPerformed(evt);
            }
        });

        okBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancleBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancleBtn.setText("Cancle");
        cancleBtn.setToolTipText("");

        javax.swing.GroupLayout sequencePnlLayout = new javax.swing.GroupLayout(sequencePnl);
        sequencePnl.setLayout(sequencePnlLayout);
        sequencePnlLayout.setHorizontalGroup(
            sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sequencePnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sequencePnlLayout.createSequentialGroup()
                        .addComponent(sequenceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sequenceIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancleBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sequencePnlLayout.createSequentialGroup()
                        .addGroup(sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SequenceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sequencePnlLayout.createSequentialGroup()
                                .addComponent(loadSequenceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearSequenceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        sequencePnlLayout.setVerticalGroup(
            sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sequencePnlLayout.createSequentialGroup()
                .addGroup(sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sequenceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sequenceIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancleBtn)
                        .addComponent(okBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SequenceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sequencePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadSequenceBtn)
                    .addComponent(clearSequenceBtn))
                .addGap(19, 19, 19))
        );

        resultTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTxtActionPerformed(evt);
            }
        });

        formatSequenceBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formatSequenceBtn.setText("Format Sequence");
        formatSequenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatSequenceBtnActionPerformed(evt);
            }
        });

        computeBtn.setText("Compute sequence properties");

        quitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quitBtn.setText("Quit");
        quitBtn.setToolTipText("");

        ComputeSequencePropertiesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComputeSequencePropertiesBtn.setText("Compute Sequence properties");
        ComputeSequencePropertiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeSequencePropertiesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GeneSequenceAnalyzerpnlLayout = new javax.swing.GroupLayout(GeneSequenceAnalyzerpnl);
        GeneSequenceAnalyzerpnl.setLayout(GeneSequenceAnalyzerpnlLayout);
        GeneSequenceAnalyzerpnlLayout.setHorizontalGroup(
            GeneSequenceAnalyzerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneSequenceAnalyzerpnlLayout.createSequentialGroup()
                .addGroup(GeneSequenceAnalyzerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneSequenceAnalyzerpnlLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(GeneSequenceAnalyzerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneSequenceAnalyzerpnlLayout.createSequentialGroup()
                                .addComponent(formatSequenceBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComputeSequencePropertiesBtn)
                                .addGap(64, 64, 64)
                                .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(computeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneSequenceAnalyzerpnlLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(GeneSequenceAnalyzerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(GeneSequenceAnalyzerpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sequencePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GeneSequenceAnalyzerpnlLayout.setVerticalGroup(
            GeneSequenceAnalyzerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneSequenceAnalyzerpnlLayout.createSequentialGroup()
                .addComponent(GeneSequenceAnalyzerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(sequencePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GeneSequenceAnalyzerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneSequenceAnalyzerpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(formatSequenceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(computeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComputeSequencePropertiesBtn))
                    .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneSequenceAnalyzerpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addComponent(GeneSequenceAnalyzerpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTxtActionPerformed

    private void ComputeSequencePropertiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeSequencePropertiesBtnActionPerformed
        // TODO add your handling code here:
        set_geneTxt();
        format_geneTxt();
        int SequenceLength = geneTxt.length();
        String lenMessage = String.format("Sequence length is %d",SequenceLength, null); 
        String message = String.format("%s/n%s/n",id,lenMessage,null);
        resultTxt.setText(message);
        
    }//GEN-LAST:event_ComputeSequencePropertiesBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        set_geneFileTxt();
        SequenceTxt.setText("The file is loaded, you can press 'Load sequence' button to see it's content. ");

    }//GEN-LAST:event_okBtnActionPerformed

    private void sequenceIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequenceIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sequenceIdTxtActionPerformed

    private void loadSequenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSequenceBtnActionPerformed
        // TODO add your handling code here:
        SequenceTxt.setText(geneFileTxt);
    }//GEN-LAST:event_loadSequenceBtnActionPerformed

    private void clearSequenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSequenceBtnActionPerformed
        // TODO add your handling code here:
        SequenceTxt.setText("");
    }//GEN-LAST:event_clearSequenceBtnActionPerformed

    private void formatSequenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatSequenceBtnActionPerformed
        // TODO add your handling code here:
         format_geneTxt();
         SequenceTxt.setText(geneTxt);
    }//GEN-LAST:event_formatSequenceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComputeSequencePropertiesBtn;
    private java.awt.Label GeneSequenceAnalyzerlbl;
    private javax.swing.JPanel GeneSequenceAnalyzerpnl;
    private javax.swing.JTextField SequenceTxt;
    private javax.swing.JButton cancleBtn;
    private javax.swing.JButton clearSequenceBtn;
    private javax.swing.JButton computeBtn;
    private javax.swing.JButton formatSequenceBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton loadSequenceBtn;
    private javax.swing.JButton quitBtn;
    private javax.swing.JTextField resultTxt;
    private javax.swing.JTextField sequenceIdTxt;
    private javax.swing.JPanel sequencePnl;
    // End of variables declaration//GEN-END:variables

    private static String gene(java.lang.String addName) {
        org.me.geneload.GeneLoadWS_Service service = new org.me.geneload.GeneLoadWS_Service();
        org.me.geneload.GeneLoadWS port = service.getGeneLoadWSPort();
        return port.gene(addName);
    }



   

}
